# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EntryWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(533, 607)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 513, 561))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_top_info = QtWidgets.QLabel(self.widget)
        self.label_top_info.setMinimumSize(QtCore.QSize(511, 21))
        self.label_top_info.setMaximumSize(QtCore.QSize(511, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_top_info.setFont(font)
        self.label_top_info.setObjectName("label_top_info")
        self.verticalLayout.addWidget(self.label_top_info)
        self.groupBox_excel_file = QtWidgets.QGroupBox(self.widget)
        self.groupBox_excel_file.setMinimumSize(QtCore.QSize(511, 281))
        self.groupBox_excel_file.setMaximumSize(QtCore.QSize(511, 281))
        self.groupBox_excel_file.setObjectName("groupBox_excel_file")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_excel_file)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 461, 142))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_select_excel = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_select_excel.setMinimumSize(QtCore.QSize(80, 29))
        self.btn_select_excel.setMaximumSize(QtCore.QSize(80, 29))
        self.btn_select_excel.setObjectName("btn_select_excel")
        self.gridLayout_2.addWidget(self.btn_select_excel, 8, 1, 1, 1)
        self.btn_re_view_excel = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_re_view_excel.setMinimumSize(QtCore.QSize(80, 29))
        self.btn_re_view_excel.setMaximumSize(QtCore.QSize(80, 29))
        self.btn_re_view_excel.setObjectName("btn_re_view_excel")
        self.gridLayout_2.addWidget(self.btn_re_view_excel, 9, 1, 1, 1)
        self.listWidget_excel_list = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.listWidget_excel_list.setMinimumSize(QtCore.QSize(373, 140))
        self.listWidget_excel_list.setMaximumSize(QtCore.QSize(373, 140))
        self.listWidget_excel_list.setObjectName("listWidget_excel_list")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_excel_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_excel_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_excel_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_excel_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_excel_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_excel_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_excel_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_excel_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_excel_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_excel_list.addItem(item)
        self.gridLayout_2.addWidget(self.listWidget_excel_list, 7, 0, 4, 1)
        self.groupBox_excel_info = QtWidgets.QGroupBox(self.groupBox_excel_file)
        self.groupBox_excel_info.setGeometry(QtCore.QRect(20, 190, 461, 81))
        self.groupBox_excel_info.setMinimumSize(QtCore.QSize(461, 81))
        self.groupBox_excel_info.setMaximumSize(QtCore.QSize(461, 81))
        self.groupBox_excel_info.setObjectName("groupBox_excel_info")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_excel_info)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 40, 357, 33))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_excel_sheet = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_excel_sheet.setMinimumSize(QtCore.QSize(201, 31))
        self.comboBox_excel_sheet.setMaximumSize(QtCore.QSize(201, 31))
        self.comboBox_excel_sheet.setObjectName("comboBox_excel_sheet")
        self.comboBox_excel_sheet.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_excel_sheet)
        self.comboBox_get_col = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_get_col.setMinimumSize(QtCore.QSize(71, 31))
        self.comboBox_get_col.setMaximumSize(QtCore.QSize(71, 31))
        self.comboBox_get_col.setObjectName("comboBox_get_col")
        self.comboBox_get_col.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_get_col)
        self.comboBox_get_row = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_get_row.setMinimumSize(QtCore.QSize(71, 31))
        self.comboBox_get_row.setMaximumSize(QtCore.QSize(71, 31))
        self.comboBox_get_row.setObjectName("comboBox_get_row")
        self.comboBox_get_row.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_get_row)
        self.verticalLayout.addWidget(self.groupBox_excel_file)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox_advance = QtWidgets.QCheckBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_advance.sizePolicy().hasHeightForWidth())
        self.checkBox_advance.setSizePolicy(sizePolicy)
        self.checkBox_advance.setMinimumSize(QtCore.QSize(91, 27))
        self.checkBox_advance.setMaximumSize(QtCore.QSize(91, 27))
        self.checkBox_advance.setChecked(False)
        self.checkBox_advance.setObjectName("checkBox_advance")
        self.gridLayout_4.addWidget(self.checkBox_advance, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(388, 21))
        self.label_2.setMaximumSize(QtCore.QSize(428, 21))
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 2)
        self.btn_start = QtWidgets.QPushButton(self.widget)
        self.btn_start.setMinimumSize(QtCore.QSize(231, 29))
        self.btn_start.setMaximumSize(QtCore.QSize(231, 29))
        self.btn_start.setObjectName("btn_start")
        self.gridLayout_4.addWidget(self.btn_start, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.groupBox_advance = QtWidgets.QGroupBox(self.widget)
        self.groupBox_advance.setMinimumSize(QtCore.QSize(511, 181))
        self.groupBox_advance.setMaximumSize(QtCore.QSize(511, 181))
        self.groupBox_advance.setMouseTracking(False)
        self.groupBox_advance.setObjectName("groupBox_advance")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_advance)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 481, 121))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_page_control = QtWidgets.QGroupBox(self.gridLayoutWidget_2)
        self.groupBox_page_control.setMinimumSize(QtCore.QSize(479, 84))
        self.groupBox_page_control.setMaximumSize(QtCore.QSize(479, 84))
        self.groupBox_page_control.setObjectName("groupBox_page_control")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_page_control)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 40, 411, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox_get_page = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_get_page.setMinimumSize(QtCore.QSize(255, 29))
        self.comboBox_get_page.setMaximumSize(QtCore.QSize(255, 29))
        self.comboBox_get_page.setObjectName("comboBox_get_page")
        self.horizontalLayout_2.addWidget(self.comboBox_get_page)
        self.btn_page_control = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_page_control.setMinimumSize(QtCore.QSize(71, 29))
        self.btn_page_control.setMaximumSize(QtCore.QSize(71, 29))
        self.btn_page_control.setObjectName("btn_page_control")
        self.horizontalLayout_2.addWidget(self.btn_page_control)
        self.btn_re_page_view = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_re_page_view.setMinimumSize(QtCore.QSize(71, 29))
        self.btn_re_page_view.setMaximumSize(QtCore.QSize(71, 29))
        self.btn_re_page_view.setObjectName("btn_re_page_view")
        self.horizontalLayout_2.addWidget(self.btn_re_page_view)
        self.gridLayout_3.addWidget(self.groupBox_page_control, 4, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(88, 26, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.btn_click_checkbox = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_click_checkbox.setMinimumSize(QtCore.QSize(221, 29))
        self.btn_click_checkbox.setMaximumSize(QtCore.QSize(221, 29))
        self.btn_click_checkbox.setObjectName("btn_click_checkbox")
        self.gridLayout_3.addWidget(self.btn_click_checkbox, 0, 0, 1, 1)
        self.btn_about = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_about.setMinimumSize(QtCore.QSize(111, 29))
        self.btn_about.setMaximumSize(QtCore.QSize(111, 29))
        self.btn_about.setObjectName("btn_about")
        self.gridLayout_3.addWidget(self.btn_about, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_advance)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_top_info.setText(_translate("MainWindow", "软件关闭后浏览器也会同关闭，如需要浏览器请不要关闭此程序"))
        self.groupBox_excel_file.setTitle(_translate("MainWindow", "请选择需要的 Excel 文件"))
        self.btn_select_excel.setText(_translate("MainWindow", "选择"))
        self.btn_re_view_excel.setText(_translate("MainWindow", "刷新显示"))
        self.listWidget_excel_list.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.listWidget_excel_list.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        __sortingEnabled = self.listWidget_excel_list.isSortingEnabled()
        self.listWidget_excel_list.setSortingEnabled(False)
        item = self.listWidget_excel_list.item(0)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_excel_list.item(1)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_excel_list.item(2)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_excel_list.item(3)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_excel_list.item(4)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_excel_list.item(5)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_excel_list.item(6)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_excel_list.item(7)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_excel_list.item(8)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_excel_list.item(9)
        item.setText(_translate("MainWindow", "新建项目"))
        self.listWidget_excel_list.setSortingEnabled(__sortingEnabled)
        self.groupBox_excel_info.setTitle(_translate("MainWindow", "Excel 读取内容设置"))
        self.comboBox_excel_sheet.setItemText(0, _translate("MainWindow", "请选择Sheet"))
        self.comboBox_get_col.setItemText(0, _translate("MainWindow", "列"))
        self.comboBox_get_row.setItemText(0, _translate("MainWindow", "行"))
        self.checkBox_advance.setText(_translate("MainWindow", "高级选项"))
        self.label_2.setText(_translate("MainWindow", "请到需要录成绩的页面并选择Excel后再点击开始按钮"))
        self.btn_start.setText(_translate("MainWindow", "开始录入"))
        self.groupBox_advance.setTitle(_translate("MainWindow", "高级"))
        self.groupBox_page_control.setTitle(_translate("MainWindow", "选择需要控制的浏览器页面,只有该页面会被程序控制"))
        self.btn_page_control.setText(_translate("MainWindow", "选择"))
        self.btn_re_page_view.setText(_translate("MainWindow", "刷新显示"))
        self.btn_click_checkbox.setText(_translate("MainWindow", "点击页面中的所有CheckBox"))
        self.btn_about.setText(_translate("MainWindow", "联系"))

