# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EntryWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(503, 673)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBox_advance = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_advance.setGeometry(QtCore.QRect(10, 500, 91, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_advance.sizePolicy().hasHeightForWidth())
        self.checkBox_advance.setSizePolicy(sizePolicy)
        self.checkBox_advance.setMinimumSize(QtCore.QSize(91, 27))
        self.checkBox_advance.setMaximumSize(QtCore.QSize(91, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_advance.setFont(font)
        self.checkBox_advance.setChecked(False)
        self.checkBox_advance.setObjectName("checkBox_advance")
        self.groupBox_excel_file = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_excel_file.setGeometry(QtCore.QRect(10, 10, 481, 351))
        self.groupBox_excel_file.setObjectName("groupBox_excel_file")
        self.groupBox_excel_info = QtWidgets.QGroupBox(self.groupBox_excel_file)
        self.groupBox_excel_info.setGeometry(QtCore.QRect(10, 190, 461, 151))
        self.groupBox_excel_info.setObjectName("groupBox_excel_info")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_excel_info)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 30, 363, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_excel_sheet = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_excel_sheet.setMinimumSize(QtCore.QSize(361, 31))
        self.comboBox_excel_sheet.setMaximumSize(QtCore.QSize(361, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_excel_sheet.setFont(font)
        self.comboBox_excel_sheet.setObjectName("comboBox_excel_sheet")
        self.comboBox_excel_sheet.addItem("")
        self.gridLayout.addWidget(self.comboBox_excel_sheet, 0, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 2)
        self.comboBox_get_row = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_get_row.setMinimumSize(QtCore.QSize(171, 31))
        self.comboBox_get_row.setMaximumSize(QtCore.QSize(171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_get_row.setFont(font)
        self.comboBox_get_row.setObjectName("comboBox_get_row")
        self.comboBox_get_row.addItem("")
        self.gridLayout.addWidget(self.comboBox_get_row, 2, 0, 1, 1)
        self.comboBox_get_col = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_get_col.setMinimumSize(QtCore.QSize(171, 31))
        self.comboBox_get_col.setMaximumSize(QtCore.QSize(171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_get_col.setFont(font)
        self.comboBox_get_col.setObjectName("comboBox_get_col")
        self.comboBox_get_col.addItem("")
        self.gridLayout.addWidget(self.comboBox_get_col, 2, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_excel_file)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 460, 146))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listWidget_excel_list = QtWidgets.QListWidget(self.layoutWidget1)
        self.listWidget_excel_list.setMinimumSize(QtCore.QSize(361, 140))
        self.listWidget_excel_list.setMaximumSize(QtCore.QSize(361, 140))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listWidget_excel_list.setFont(font)
        self.listWidget_excel_list.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listWidget_excel_list.setObjectName("listWidget_excel_list")
        self.gridLayout_2.addWidget(self.listWidget_excel_list, 0, 0, 4, 1)
        self.btn_select_excel = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_select_excel.setMinimumSize(QtCore.QSize(91, 51))
        self.btn_select_excel.setMaximumSize(QtCore.QSize(91, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_select_excel.setFont(font)
        self.btn_select_excel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_select_excel.setObjectName("btn_select_excel")
        self.gridLayout_2.addWidget(self.btn_select_excel, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(88, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.btn_re_view_excel = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_re_view_excel.setMinimumSize(QtCore.QSize(91, 31))
        self.btn_re_view_excel.setMaximumSize(QtCore.QSize(91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.btn_re_view_excel.setFont(font)
        self.btn_re_view_excel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_re_view_excel.setObjectName("btn_re_view_excel")
        self.gridLayout_2.addWidget(self.btn_re_view_excel, 2, 1, 1, 1)
        self.btn_open_dir = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_open_dir.setMinimumSize(QtCore.QSize(91, 31))
        self.btn_open_dir.setMaximumSize(QtCore.QSize(91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_open_dir.setFont(font)
        self.btn_open_dir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_open_dir.setObjectName("btn_open_dir")
        self.gridLayout_2.addWidget(self.btn_open_dir, 3, 1, 1, 1)
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(40, 400, 411, 41))
        self.btn_start.setMinimumSize(QtCore.QSize(411, 41))
        self.btn_start.setMaximumSize(QtCore.QSize(411, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_start.setFont(font)
        self.btn_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_start.setObjectName("btn_start")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 370, 399, 21))
        self.label_2.setMinimumSize(QtCore.QSize(399, 21))
        self.label_2.setMaximumSize(QtCore.QSize(399, 21))
        self.label_2.setObjectName("label_2")
        self.btn_click_checkbox = QtWidgets.QPushButton(self.centralwidget)
        self.btn_click_checkbox.setGeometry(QtCore.QRect(40, 450, 411, 41))
        self.btn_click_checkbox.setMinimumSize(QtCore.QSize(411, 41))
        self.btn_click_checkbox.setMaximumSize(QtCore.QSize(411, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_click_checkbox.setFont(font)
        self.btn_click_checkbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_click_checkbox.setObjectName("btn_click_checkbox")
        self.groupBox_advance = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_advance.setGeometry(QtCore.QRect(10, 550, 481, 91))
        self.groupBox_advance.setMouseTracking(False)
        self.groupBox_advance.setObjectName("groupBox_advance")
        self.btn_clean_log = QtWidgets.QPushButton(self.groupBox_advance)
        self.btn_clean_log.setGeometry(QtCore.QRect(250, 30, 211, 41))
        self.btn_clean_log.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_clean_log.setObjectName("btn_clean_log")
        self.btn_re_open_browser = QtWidgets.QPushButton(self.groupBox_advance)
        self.btn_re_open_browser.setGeometry(QtCore.QRect(20, 30, 211, 41))
        self.btn_re_open_browser.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_re_open_browser.setObjectName("btn_re_open_browser")
        self.groupBox_about_info = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_about_info.setEnabled(True)
        self.groupBox_about_info.setGeometry(QtCore.QRect(10, 530, 481, 111))
        self.groupBox_about_info.setObjectName("groupBox_about_info")
        self.ecjtu_logo_label = QtWidgets.QLabel(self.groupBox_about_info)
        self.ecjtu_logo_label.setGeometry(QtCore.QRect(20, 20, 81, 81))
        self.ecjtu_logo_label.setObjectName("ecjtu_logo_label")
        self.label_speace_insititute = QtWidgets.QLabel(self.groupBox_about_info)
        self.label_speace_insititute.setGeometry(QtCore.QRect(130, 20, 201, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_speace_insititute.setFont(font)
        self.label_speace_insititute.setObjectName("label_speace_insititute")
        self.commandLinkButton_feedback = QtWidgets.QCommandLinkButton(self.groupBox_about_info)
        self.commandLinkButton_feedback.setGeometry(QtCore.QRect(350, 40, 121, 41))
        self.commandLinkButton_feedback.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton_feedback.setObjectName("commandLinkButton_feedback")
        self.checkBox_advance.raise_()
        self.groupBox_excel_file.raise_()
        self.btn_start.raise_()
        self.label_2.raise_()
        self.btn_click_checkbox.raise_()
        self.groupBox_about_info.raise_()
        self.groupBox_advance.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "华东交通大学"))
        self.checkBox_advance.setText(_translate("MainWindow", "高级选项"))
        self.groupBox_excel_file.setTitle(_translate("MainWindow", "请选择需要的 Excel 文件"))
        self.groupBox_excel_info.setTitle(_translate("MainWindow", "Excel 读取内容设置"))
        self.comboBox_excel_sheet.setItemText(0, _translate("MainWindow", "请先选择Excel文件"))
        self.label.setText(_translate("MainWindow", "请选择<b>第一个成绩</b>所在的行列"))
        self.comboBox_get_row.setItemText(0, _translate("MainWindow", "请先选择Excel"))
        self.comboBox_get_col.setItemText(0, _translate("MainWindow", "请先选择Excel"))
        self.listWidget_excel_list.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.listWidget_excel_list.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.btn_select_excel.setText(_translate("MainWindow", "选择"))
        self.btn_re_view_excel.setText(_translate("MainWindow", "刷新"))
        self.btn_open_dir.setText(_translate("MainWindow", "打开"))
        self.btn_start.setText(_translate("MainWindow", "开始录入"))
        self.label_2.setText(_translate("MainWindow", "请到需要录成绩的页面再点击开始按钮"))
        self.btn_click_checkbox.setText(_translate("MainWindow", "点击页面中的所有CheckBox"))
        self.groupBox_advance.setTitle(_translate("MainWindow", "高级"))
        self.btn_clean_log.setText(_translate("MainWindow", "清空日志文件"))
        self.btn_re_open_browser.setText(_translate("MainWindow", "再次打开浏览器"))
        self.groupBox_about_info.setTitle(_translate("MainWindow", "关于"))
        self.ecjtu_logo_label.setText(_translate("MainWindow", "ecjtu_logo_img"))
        self.label_speace_insititute.setText(_translate("MainWindow", " 华东交通大学软件学院\n"
" 和平研究院"))
        self.commandLinkButton_feedback.setText(_translate("MainWindow", "问题反馈"))

