# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EntryWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(782, 873)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 490, 401, 51))
        self.label_2.setObjectName("label_2")
        self.label_top_info = QtWidgets.QLabel(self.centralwidget)
        self.label_top_info.setGeometry(QtCore.QRect(20, 10, 781, 30))
        self.label_top_info.setMaximumSize(QtCore.QSize(901, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_top_info.setFont(font)
        self.label_top_info.setObjectName("label_top_info")
        self.groupBox_excel_file = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_excel_file.setGeometry(QtCore.QRect(20, 50, 741, 431))
        self.groupBox_excel_file.setObjectName("groupBox_excel_file")
        self.groupBox_excel_info = QtWidgets.QGroupBox(self.groupBox_excel_file)
        self.groupBox_excel_info.setGeometry(QtCore.QRect(20, 250, 701, 161))
        self.groupBox_excel_info.setObjectName("groupBox_excel_info")
        self.comboBox_excel_sheet = QtWidgets.QComboBox(self.groupBox_excel_info)
        self.comboBox_excel_sheet.setGeometry(QtCore.QRect(30, 40, 221, 41))
        self.comboBox_excel_sheet.setObjectName("comboBox_excel_sheet")
        self.comboBox_excel_sheet.addItem("")
        self.comboBox_get_mode = QtWidgets.QComboBox(self.groupBox_excel_info)
        self.comboBox_get_mode.setGeometry(QtCore.QRect(30, 100, 171, 41))
        self.comboBox_get_mode.setObjectName("comboBox_get_mode")
        self.comboBox_get_mode.addItem("")
        self.comboBox_get_mode.addItem("")
        self.comboBox_get_row = QtWidgets.QComboBox(self.groupBox_excel_info)
        self.comboBox_get_row.setGeometry(QtCore.QRect(240, 100, 91, 41))
        self.comboBox_get_row.setObjectName("comboBox_get_row")
        self.comboBox_get_row.addItem("")
        self.comboBox_get_col = QtWidgets.QComboBox(self.groupBox_excel_info)
        self.comboBox_get_col.setGeometry(QtCore.QRect(370, 100, 91, 41))
        self.comboBox_get_col.setObjectName("comboBox_get_col")
        self.comboBox_get_col.addItem("")
        self.listWidget_excel_list = QtWidgets.QListWidget(self.groupBox_excel_file)
        self.listWidget_excel_list.setGeometry(QtCore.QRect(20, 30, 561, 201))
        self.listWidget_excel_list.setObjectName("listWidget_excel_list")
        self.btn_select_excel = QtWidgets.QPushButton(self.groupBox_excel_file)
        self.btn_select_excel.setGeometry(QtCore.QRect(610, 60, 101, 51))
        self.btn_select_excel.setObjectName("btn_select_excel")
        self.btn_re_view_excel = QtWidgets.QPushButton(self.groupBox_excel_file)
        self.btn_re_view_excel.setGeometry(QtCore.QRect(610, 140, 101, 51))
        self.btn_re_view_excel.setObjectName("btn_re_view_excel")
        self.groupBox_advance = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_advance.setGeometry(QtCore.QRect(20, 610, 741, 231))
        self.groupBox_advance.setMouseTracking(False)
        self.groupBox_advance.setObjectName("groupBox_advance")
        self.groupBox_page_control = QtWidgets.QGroupBox(self.groupBox_advance)
        self.groupBox_page_control.setGeometry(QtCore.QRect(20, 90, 681, 121))
        self.groupBox_page_control.setObjectName("groupBox_page_control")
        self.comboBox_get_page = QtWidgets.QComboBox(self.groupBox_page_control)
        self.comboBox_get_page.setGeometry(QtCore.QRect(30, 50, 361, 41))
        self.comboBox_get_page.setObjectName("comboBox_get_page")
        self.btn_page_control = QtWidgets.QPushButton(self.groupBox_page_control)
        self.btn_page_control.setGeometry(QtCore.QRect(430, 50, 101, 41))
        self.btn_page_control.setObjectName("btn_page_control")
        self.btn_re_page_view = QtWidgets.QPushButton(self.groupBox_page_control)
        self.btn_re_page_view.setGeometry(QtCore.QRect(550, 50, 101, 41))
        self.btn_re_page_view.setObjectName("btn_re_page_view")
        self.btn_click_checkbox = QtWidgets.QPushButton(self.groupBox_advance)
        self.btn_click_checkbox.setGeometry(QtCore.QRect(20, 30, 271, 51))
        self.btn_click_checkbox.setObjectName("btn_click_checkbox")
        self.checkBox_advance = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_advance.setGeometry(QtCore.QRect(20, 560, 91, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_advance.sizePolicy().hasHeightForWidth())
        self.checkBox_advance.setSizePolicy(sizePolicy)
        self.checkBox_advance.setChecked(False)
        self.checkBox_advance.setObjectName("checkBox_advance")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(520, 490, 221, 51))
        self.btn_start.setObjectName("btn_start")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.listWidget_excel_list, self.btn_select_excel)
        MainWindow.setTabOrder(self.btn_select_excel, self.btn_page_control)
        MainWindow.setTabOrder(self.btn_page_control, self.comboBox_get_page)
        MainWindow.setTabOrder(self.comboBox_get_page, self.btn_re_view_excel)
        MainWindow.setTabOrder(self.btn_re_view_excel, self.comboBox_get_mode)
        MainWindow.setTabOrder(self.comboBox_get_mode, self.comboBox_excel_sheet)
        MainWindow.setTabOrder(self.comboBox_excel_sheet, self.comboBox_get_row)
        MainWindow.setTabOrder(self.comboBox_get_row, self.comboBox_get_col)
        MainWindow.setTabOrder(self.comboBox_get_col, self.btn_start)
        MainWindow.setTabOrder(self.btn_start, self.btn_re_page_view)
        MainWindow.setTabOrder(self.btn_re_page_view, self.checkBox_advance)
        MainWindow.setTabOrder(self.checkBox_advance, self.btn_click_checkbox)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "请到需要录成绩的页面并选择Excel后再点击开始按钮"))
        self.label_top_info.setText(_translate("MainWindow", "软件关闭后浏览器也会同关闭，如需要浏览器请不要关闭此程序"))
        self.groupBox_excel_file.setTitle(_translate("MainWindow", "请选择需要的 Excel 文件"))
        self.groupBox_excel_info.setTitle(_translate("MainWindow", "Excel 读取内容设置"))
        self.comboBox_excel_sheet.setItemText(0, _translate("MainWindow", "请选择Sheet"))
        self.comboBox_get_mode.setItemText(0, _translate("MainWindow", "成绩按列存放"))
        self.comboBox_get_mode.setItemText(1, _translate("MainWindow", "成绩按行存放"))
        self.comboBox_get_row.setItemText(0, _translate("MainWindow", "行"))
        self.comboBox_get_col.setItemText(0, _translate("MainWindow", "列"))
        self.listWidget_excel_list.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.listWidget_excel_list.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.btn_select_excel.setText(_translate("MainWindow", "选择"))
        self.btn_re_view_excel.setText(_translate("MainWindow", "刷新显示"))
        self.groupBox_advance.setTitle(_translate("MainWindow", "高级"))
        self.groupBox_page_control.setTitle(_translate("MainWindow", "选择需要控制的浏览器页面,只有该页面会被程序控制"))
        self.btn_page_control.setText(_translate("MainWindow", "选择"))
        self.btn_re_page_view.setText(_translate("MainWindow", "刷新显示"))
        self.btn_click_checkbox.setText(_translate("MainWindow", "点击页面中的所有CheckBox"))
        self.checkBox_advance.setText(_translate("MainWindow", "高级选项"))
        self.btn_start.setText(_translate("MainWindow", "开始录入"))

