# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(561, 687)
        MainWindow.setMinimumSize(QtCore.QSize(561, 687))
        MainWindow.setMaximumSize(QtCore.QSize(561, 687))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBox_advance = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_advance.setGeometry(QtCore.QRect(20, 510, 91, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_advance.sizePolicy().hasHeightForWidth())
        self.checkBox_advance.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_advance.setFont(font)
        self.checkBox_advance.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_advance.setChecked(False)
        self.checkBox_advance.setObjectName("checkBox_advance")
        self.groupBox_excel_file = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_excel_file.setGeometry(QtCore.QRect(20, 10, 521, 341))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.groupBox_excel_file.setFont(font)
        self.groupBox_excel_file.setObjectName("groupBox_excel_file")
        self.groupBox_excel_info = QtWidgets.QGroupBox(self.groupBox_excel_file)
        self.groupBox_excel_info.setGeometry(QtCore.QRect(30, 190, 461, 141))
        self.groupBox_excel_info.setObjectName("groupBox_excel_info")
        self.widget = QtWidgets.QWidget(self.groupBox_excel_info)
        self.widget.setGeometry(QtCore.QRect(30, 20, 413, 107))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.cur_excel_name_label = QtWidgets.QLabel(self.widget)
        self.cur_excel_name_label.setMinimumSize(QtCore.QSize(141, 31))
        self.cur_excel_name_label.setMaximumSize(QtCore.QSize(141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.cur_excel_name_label.setFont(font)
        self.cur_excel_name_label.setObjectName("cur_excel_name_label")
        self.gridLayout.addWidget(self.cur_excel_name_label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.comboBox_excel_sheet = QtWidgets.QComboBox(self.widget)
        self.comboBox_excel_sheet.setMinimumSize(QtCore.QSize(241, 31))
        self.comboBox_excel_sheet.setMaximumSize(QtCore.QSize(241, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_excel_sheet.setFont(font)
        self.comboBox_excel_sheet.setObjectName("comboBox_excel_sheet")
        self.comboBox_excel_sheet.addItem("")
        self.gridLayout.addWidget(self.comboBox_excel_sheet, 0, 2, 1, 2)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(401, 31))
        self.label.setMaximumSize(QtCore.QSize(401, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 4)
        self.comboBox_get_row = QtWidgets.QComboBox(self.widget)
        self.comboBox_get_row.setMinimumSize(QtCore.QSize(181, 31))
        self.comboBox_get_row.setMaximumSize(QtCore.QSize(181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_get_row.setFont(font)
        self.comboBox_get_row.setObjectName("comboBox_get_row")
        self.comboBox_get_row.addItem("")
        self.gridLayout.addWidget(self.comboBox_get_row, 2, 0, 1, 3)
        self.comboBox_get_col = QtWidgets.QComboBox(self.widget)
        self.comboBox_get_col.setMinimumSize(QtCore.QSize(181, 31))
        self.comboBox_get_col.setMaximumSize(QtCore.QSize(181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_get_col.setFont(font)
        self.comboBox_get_col.setObjectName("comboBox_get_col")
        self.comboBox_get_col.addItem("")
        self.gridLayout.addWidget(self.comboBox_get_col, 2, 3, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.groupBox_excel_file)
        self.widget1.setGeometry(QtCore.QRect(31, 30, 466, 146))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listWidget_excel_list = QtWidgets.QListWidget(self.widget1)
        self.listWidget_excel_list.setMinimumSize(QtCore.QSize(377, 144))
        self.listWidget_excel_list.setMaximumSize(QtCore.QSize(377, 144))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listWidget_excel_list.setFont(font)
        self.listWidget_excel_list.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.listWidget_excel_list.setObjectName("listWidget_excel_list")
        self.gridLayout_2.addWidget(self.listWidget_excel_list, 0, 0, 4, 1)
        self.btn_select_excel = QtWidgets.QPushButton(self.widget1)
        self.btn_select_excel.setMinimumSize(QtCore.QSize(81, 31))
        self.btn_select_excel.setMaximumSize(QtCore.QSize(81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btn_select_excel.setFont(font)
        self.btn_select_excel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_select_excel.setObjectName("btn_select_excel")
        self.gridLayout_2.addWidget(self.btn_select_excel, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(71, 21, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 1)
        self.btn_re_view_excel = QtWidgets.QPushButton(self.widget1)
        self.btn_re_view_excel.setMinimumSize(QtCore.QSize(81, 31))
        self.btn_re_view_excel.setMaximumSize(QtCore.QSize(81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.btn_re_view_excel.setFont(font)
        self.btn_re_view_excel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_re_view_excel.setObjectName("btn_re_view_excel")
        self.gridLayout_2.addWidget(self.btn_re_view_excel, 2, 1, 1, 1)
        self.btn_open_dir = QtWidgets.QPushButton(self.widget1)
        self.btn_open_dir.setMinimumSize(QtCore.QSize(81, 31))
        self.btn_open_dir.setMaximumSize(QtCore.QSize(81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.btn_open_dir.setFont(font)
        self.btn_open_dir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_open_dir.setObjectName("btn_open_dir")
        self.gridLayout_2.addWidget(self.btn_open_dir, 3, 1, 1, 1)
        self.groupBox_about_info = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_about_info.setEnabled(True)
        self.groupBox_about_info.setGeometry(QtCore.QRect(20, 540, 521, 111))
        self.groupBox_about_info.setObjectName("groupBox_about_info")
        self.ecjtu_logo_label = QtWidgets.QLabel(self.groupBox_about_info)
        self.ecjtu_logo_label.setGeometry(QtCore.QRect(20, 20, 81, 81))
        self.ecjtu_logo_label.setObjectName("ecjtu_logo_label")
        self.label_speace_insititute = QtWidgets.QLabel(self.groupBox_about_info)
        self.label_speace_insititute.setGeometry(QtCore.QRect(140, 20, 221, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_speace_insititute.setFont(font)
        self.label_speace_insititute.setObjectName("label_speace_insititute")
        self.commandLinkButton_feedback = QtWidgets.QCommandLinkButton(self.groupBox_about_info)
        self.commandLinkButton_feedback.setGeometry(QtCore.QRect(380, 40, 121, 41))
        self.commandLinkButton_feedback.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton_feedback.setObjectName("commandLinkButton_feedback")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 370, 521, 131))
        self.groupBox.setObjectName("groupBox")
        self.btn_click_checkbox = QtWidgets.QPushButton(self.groupBox)
        self.btn_click_checkbox.setGeometry(QtCore.QRect(20, 30, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_click_checkbox.setFont(font)
        self.btn_click_checkbox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_click_checkbox.setObjectName("btn_click_checkbox")
        self.level_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.level_comboBox.setGeometry(QtCore.QRect(230, 31, 271, 39))
        self.level_comboBox.setObjectName("level_comboBox")
        self.btn_start = QtWidgets.QPushButton(self.groupBox)
        self.btn_start.setGeometry(QtCore.QRect(230, 80, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_start.setFont(font)
        self.btn_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_start.setObjectName("btn_start")
        self.btn_clean_input = QtWidgets.QPushButton(self.groupBox)
        self.btn_clean_input.setGeometry(QtCore.QRect(20, 80, 181, 41))
        self.btn_clean_input.setObjectName("btn_clean_input")
        self.groupBox_advance = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_advance.setGeometry(QtCore.QRect(20, 540, 521, 91))
        self.groupBox_advance.setMouseTracking(False)
        self.groupBox_advance.setObjectName("groupBox_advance")
        self.btn_clean_log = QtWidgets.QPushButton(self.groupBox_advance)
        self.btn_clean_log.setGeometry(QtCore.QRect(180, 30, 141, 41))
        self.btn_clean_log.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_clean_log.setObjectName("btn_clean_log")
        self.btn_re_open_browser = QtWidgets.QPushButton(self.groupBox_advance)
        self.btn_re_open_browser.setGeometry(QtCore.QRect(10, 30, 161, 41))
        self.btn_re_open_browser.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_re_open_browser.setObjectName("btn_re_open_browser")
        self.btn_map = QtWidgets.QPushButton(self.groupBox_advance)
        self.btn_map.setGeometry(QtCore.QRect(330, 30, 181, 41))
        self.btn_map.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_map.setObjectName("btn_map")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "华东交通大学"))
        self.checkBox_advance.setText(_translate("MainWindow", "高级选项"))
        self.groupBox_excel_file.setTitle(_translate("MainWindow", "选择 Excel 文件"))
        self.groupBox_excel_info.setTitle(_translate("MainWindow", "Excel 内容选取"))
        self.cur_excel_name_label.setText(_translate("MainWindow", "请选择Excel"))
        self.comboBox_excel_sheet.setItemText(0, _translate("MainWindow", "请先选择Excel文件"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>第一个成绩的行列</p></body></html>"))
        self.comboBox_get_row.setItemText(0, _translate("MainWindow", "请先选择Excel"))
        self.comboBox_get_col.setItemText(0, _translate("MainWindow", "请先选择Excel"))
        self.listWidget_excel_list.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.listWidget_excel_list.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.btn_select_excel.setText(_translate("MainWindow", "选择"))
        self.btn_re_view_excel.setText(_translate("MainWindow", "刷新"))
        self.btn_open_dir.setText(_translate("MainWindow", "打开文件夹"))
        self.groupBox_about_info.setTitle(_translate("MainWindow", "关于"))
        self.ecjtu_logo_label.setText(_translate("MainWindow", "ecjtu_logo_img"))
        self.label_speace_insititute.setText(_translate("MainWindow", " 华东交通大学 - 软件学院\n"
" 和平研究院"))
        self.commandLinkButton_feedback.setText(_translate("MainWindow", "关于"))
        self.groupBox.setTitle(_translate("MainWindow", "请到需要录成绩的页面再点击开始按钮"))
        self.btn_click_checkbox.setText(_translate("MainWindow", "点击复选框"))
        self.btn_start.setText(_translate("MainWindow", "开始录入"))
        self.btn_clean_input.setText(_translate("MainWindow", "清空输入"))
        self.groupBox_advance.setTitle(_translate("MainWindow", "高级"))
        self.btn_clean_log.setText(_translate("MainWindow", "清空日志文件"))
        self.btn_re_open_browser.setText(_translate("MainWindow", "重新打开浏览器"))
        self.btn_map.setText(_translate("MainWindow", "更改等级成绩映射"))

