# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MapWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MapDialog(object):
    def setupUi(self, MapDialog):
        MapDialog.setObjectName("MapDialog")
        MapDialog.resize(681, 694)
        self.btn_hundred = QtWidgets.QPushButton(MapDialog)
        self.btn_hundred.setGeometry(QtCore.QRect(60, 70, 161, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_hundred.setFont(font)
        self.btn_hundred.setObjectName("btn_hundred")
        self.btn_five = QtWidgets.QPushButton(MapDialog)
        self.btn_five.setGeometry(QtCore.QRect(260, 70, 161, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_five.setFont(font)
        self.btn_five.setObjectName("btn_five")
        self.btn_two = QtWidgets.QPushButton(MapDialog)
        self.btn_two.setGeometry(QtCore.QRect(460, 70, 161, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_two.setFont(font)
        self.btn_two.setObjectName("btn_two")
        self.label = QtWidgets.QLabel(MapDialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 371, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox_five = QtWidgets.QGroupBox(MapDialog)
        self.groupBox_five.setGeometry(QtCore.QRect(150, 150, 371, 521))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.groupBox_five.setFont(font)
        self.groupBox_five.setObjectName("groupBox_five")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_five)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 80, 270, 371))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(70, 30))
        self.label_2.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(70, 30))
        self.label_4.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(70, 30))
        self.label_3.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setMinimumSize(QtCore.QSize(70, 30))
        self.label_17.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 1, 0, 1, 1)
        self.five_now_you = QtWidgets.QLabel(self.layoutWidget)
        self.five_now_you.setMinimumSize(QtCore.QSize(70, 30))
        self.five_now_you.setMaximumSize(QtCore.QSize(70, 30))
        self.five_now_you.setObjectName("five_now_you")
        self.gridLayout.addWidget(self.five_now_you, 1, 1, 1, 1)
        self.five_edit_you = QtWidgets.QLineEdit(self.layoutWidget)
        self.five_edit_you.setMinimumSize(QtCore.QSize(114, 28))
        self.five_edit_you.setMaximumSize(QtCore.QSize(114, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.five_edit_you.setFont(font)
        self.five_edit_you.setObjectName("five_edit_you")
        self.gridLayout.addWidget(self.five_edit_you, 1, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget)
        self.label_22.setMinimumSize(QtCore.QSize(70, 30))
        self.label_22.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 2, 0, 1, 1)
        self.five_now_liang = QtWidgets.QLabel(self.layoutWidget)
        self.five_now_liang.setMinimumSize(QtCore.QSize(70, 30))
        self.five_now_liang.setMaximumSize(QtCore.QSize(70, 30))
        self.five_now_liang.setObjectName("five_now_liang")
        self.gridLayout.addWidget(self.five_now_liang, 2, 1, 1, 1)
        self.five_edit_liang = QtWidgets.QLineEdit(self.layoutWidget)
        self.five_edit_liang.setMinimumSize(QtCore.QSize(114, 28))
        self.five_edit_liang.setMaximumSize(QtCore.QSize(114, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.five_edit_liang.setFont(font)
        self.five_edit_liang.setObjectName("five_edit_liang")
        self.gridLayout.addWidget(self.five_edit_liang, 2, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setMinimumSize(QtCore.QSize(70, 30))
        self.label_20.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 3, 0, 1, 1)
        self.five_now_zhong = QtWidgets.QLabel(self.layoutWidget)
        self.five_now_zhong.setMinimumSize(QtCore.QSize(70, 30))
        self.five_now_zhong.setMaximumSize(QtCore.QSize(70, 30))
        self.five_now_zhong.setObjectName("five_now_zhong")
        self.gridLayout.addWidget(self.five_now_zhong, 3, 1, 1, 1)
        self.five_edit_zhong = QtWidgets.QLineEdit(self.layoutWidget)
        self.five_edit_zhong.setMinimumSize(QtCore.QSize(114, 28))
        self.five_edit_zhong.setMaximumSize(QtCore.QSize(114, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.five_edit_zhong.setFont(font)
        self.five_edit_zhong.setObjectName("five_edit_zhong")
        self.gridLayout.addWidget(self.five_edit_zhong, 3, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setMinimumSize(QtCore.QSize(70, 30))
        self.label_18.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 4, 0, 1, 1)
        self.five_now_jige = QtWidgets.QLabel(self.layoutWidget)
        self.five_now_jige.setMinimumSize(QtCore.QSize(70, 30))
        self.five_now_jige.setMaximumSize(QtCore.QSize(70, 30))
        self.five_now_jige.setObjectName("five_now_jige")
        self.gridLayout.addWidget(self.five_now_jige, 4, 1, 1, 1)
        self.five_edit_jige = QtWidgets.QLineEdit(self.layoutWidget)
        self.five_edit_jige.setMinimumSize(QtCore.QSize(114, 28))
        self.five_edit_jige.setMaximumSize(QtCore.QSize(114, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.five_edit_jige.setFont(font)
        self.five_edit_jige.setObjectName("five_edit_jige")
        self.gridLayout.addWidget(self.five_edit_jige, 4, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        self.label_21.setMinimumSize(QtCore.QSize(70, 30))
        self.label_21.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 5, 0, 1, 1)
        self.five_now_bujige = QtWidgets.QLabel(self.layoutWidget)
        self.five_now_bujige.setMinimumSize(QtCore.QSize(70, 30))
        self.five_now_bujige.setMaximumSize(QtCore.QSize(70, 30))
        self.five_now_bujige.setObjectName("five_now_bujige")
        self.gridLayout.addWidget(self.five_now_bujige, 5, 1, 1, 1)
        self.five_edit_bujige = QtWidgets.QLineEdit(self.layoutWidget)
        self.five_edit_bujige.setMinimumSize(QtCore.QSize(114, 28))
        self.five_edit_bujige.setMaximumSize(QtCore.QSize(114, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.five_edit_bujige.setFont(font)
        self.five_edit_bujige.setObjectName("five_edit_bujige")
        self.gridLayout.addWidget(self.five_edit_bujige, 5, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setMinimumSize(QtCore.QSize(70, 30))
        self.label_19.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 6, 0, 1, 1)
        self.five_now_mianxiu = QtWidgets.QLabel(self.layoutWidget)
        self.five_now_mianxiu.setMinimumSize(QtCore.QSize(70, 30))
        self.five_now_mianxiu.setMaximumSize(QtCore.QSize(70, 30))
        self.five_now_mianxiu.setObjectName("five_now_mianxiu")
        self.gridLayout.addWidget(self.five_now_mianxiu, 6, 1, 1, 1)
        self.five_edit_mianxiu = QtWidgets.QLineEdit(self.layoutWidget)
        self.five_edit_mianxiu.setMinimumSize(QtCore.QSize(114, 28))
        self.five_edit_mianxiu.setMaximumSize(QtCore.QSize(114, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.five_edit_mianxiu.setFont(font)
        self.five_edit_mianxiu.setObjectName("five_edit_mianxiu")
        self.gridLayout.addWidget(self.five_edit_mianxiu, 6, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget)
        self.label_23.setMinimumSize(QtCore.QSize(70, 30))
        self.label_23.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 7, 0, 1, 1)
        self.five_now_huankao = QtWidgets.QLabel(self.layoutWidget)
        self.five_now_huankao.setMinimumSize(QtCore.QSize(70, 30))
        self.five_now_huankao.setMaximumSize(QtCore.QSize(70, 30))
        self.five_now_huankao.setObjectName("five_now_huankao")
        self.gridLayout.addWidget(self.five_now_huankao, 7, 1, 1, 1)
        self.five_edit_huankao = QtWidgets.QLineEdit(self.layoutWidget)
        self.five_edit_huankao.setMinimumSize(QtCore.QSize(114, 28))
        self.five_edit_huankao.setMaximumSize(QtCore.QSize(114, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.five_edit_huankao.setFont(font)
        self.five_edit_huankao.setObjectName("five_edit_huankao")
        self.gridLayout.addWidget(self.five_edit_huankao, 7, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(70, 30))
        self.label_9.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 0, 1, 1)
        self.five_now_quekao = QtWidgets.QLabel(self.layoutWidget)
        self.five_now_quekao.setMinimumSize(QtCore.QSize(70, 30))
        self.five_now_quekao.setMaximumSize(QtCore.QSize(70, 30))
        self.five_now_quekao.setObjectName("five_now_quekao")
        self.gridLayout.addWidget(self.five_now_quekao, 8, 1, 1, 1)
        self.five_edit_quekao = QtWidgets.QLineEdit(self.layoutWidget)
        self.five_edit_quekao.setMinimumSize(QtCore.QSize(114, 28))
        self.five_edit_quekao.setMaximumSize(QtCore.QSize(114, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.five_edit_quekao.setFont(font)
        self.five_edit_quekao.setObjectName("five_edit_quekao")
        self.gridLayout.addWidget(self.five_edit_quekao, 8, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setMinimumSize(QtCore.QSize(70, 30))
        self.label_10.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 9, 0, 1, 1)
        self.five_now_quxiaozige = QtWidgets.QLabel(self.layoutWidget)
        self.five_now_quxiaozige.setMinimumSize(QtCore.QSize(70, 30))
        self.five_now_quxiaozige.setMaximumSize(QtCore.QSize(70, 30))
        self.five_now_quxiaozige.setObjectName("five_now_quxiaozige")
        self.gridLayout.addWidget(self.five_now_quxiaozige, 9, 1, 1, 1)
        self.five_edit_quxiaozige = QtWidgets.QLineEdit(self.layoutWidget)
        self.five_edit_quxiaozige.setMinimumSize(QtCore.QSize(114, 28))
        self.five_edit_quxiaozige.setMaximumSize(QtCore.QSize(114, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.five_edit_quxiaozige.setFont(font)
        self.five_edit_quxiaozige.setObjectName("five_edit_quxiaozige")
        self.gridLayout.addWidget(self.five_edit_quxiaozige, 9, 2, 1, 1)
        self.btn_five_confirm = QtWidgets.QPushButton(self.groupBox_five)
        self.btn_five_confirm.setGeometry(QtCore.QRect(100, 470, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_five_confirm.setFont(font)
        self.btn_five_confirm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_five_confirm.setObjectName("btn_five_confirm")
        self.label_tip = QtWidgets.QLabel(self.groupBox_five)
        self.label_tip.setGeometry(QtCore.QRect(50, 30, 261, 41))
        self.label_tip.setObjectName("label_tip")
        self.groupBox_hundred = QtWidgets.QGroupBox(MapDialog)
        self.groupBox_hundred.setGeometry(QtCore.QRect(150, 150, 371, 521))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox_hundred.setFont(font)
        self.groupBox_hundred.setObjectName("groupBox_hundred")
        self.hundred_double_checkBox = QtWidgets.QCheckBox(self.groupBox_hundred)
        self.hundred_double_checkBox.setGeometry(QtCore.QRect(30, 70, 241, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.hundred_double_checkBox.setFont(font)
        self.hundred_double_checkBox.setObjectName("hundred_double_checkBox")
        self.btn_hundred_confirm = QtWidgets.QPushButton(self.groupBox_hundred)
        self.btn_hundred_confirm.setGeometry(QtCore.QRect(110, 320, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_hundred_confirm.setFont(font)
        self.btn_hundred_confirm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_hundred_confirm.setObjectName("btn_hundred_confirm")
        self.groupBox_two = QtWidgets.QGroupBox(MapDialog)
        self.groupBox_two.setGeometry(QtCore.QRect(150, 150, 371, 521))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox_two.setFont(font)
        self.groupBox_two.setObjectName("groupBox_two")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_two)
        self.layoutWidget1.setGeometry(QtCore.QRect(50, 90, 270, 271))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.two_edit_quxiaozige = QtWidgets.QLineEdit(self.layoutWidget1)
        self.two_edit_quxiaozige.setMinimumSize(QtCore.QSize(114, 28))
        self.two_edit_quxiaozige.setMaximumSize(QtCore.QSize(114, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.two_edit_quxiaozige.setFont(font)
        self.two_edit_quxiaozige.setObjectName("two_edit_quxiaozige")
        self.gridLayout_2.addWidget(self.two_edit_quxiaozige, 6, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_15.setMinimumSize(QtCore.QSize(70, 30))
        self.label_15.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 2, 0, 1, 1)
        self.two_now_hege = QtWidgets.QLabel(self.layoutWidget1)
        self.two_now_hege.setMinimumSize(QtCore.QSize(70, 30))
        self.two_now_hege.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.two_now_hege.setFont(font)
        self.two_now_hege.setObjectName("two_now_hege")
        self.gridLayout_2.addWidget(self.two_now_hege, 1, 1, 1, 1)
        self.two_now_buhege = QtWidgets.QLabel(self.layoutWidget1)
        self.two_now_buhege.setMinimumSize(QtCore.QSize(70, 30))
        self.two_now_buhege.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.two_now_buhege.setFont(font)
        self.two_now_buhege.setObjectName("two_now_buhege")
        self.gridLayout_2.addWidget(self.two_now_buhege, 2, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_16.setMinimumSize(QtCore.QSize(70, 30))
        self.label_16.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_14.setMinimumSize(QtCore.QSize(70, 30))
        self.label_14.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 3, 0, 1, 1)
        self.two_now_mianxiu = QtWidgets.QLabel(self.layoutWidget1)
        self.two_now_mianxiu.setMinimumSize(QtCore.QSize(70, 30))
        self.two_now_mianxiu.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.two_now_mianxiu.setFont(font)
        self.two_now_mianxiu.setObjectName("two_now_mianxiu")
        self.gridLayout_2.addWidget(self.two_now_mianxiu, 3, 1, 1, 1)
        self.two_edit_buhege = QtWidgets.QLineEdit(self.layoutWidget1)
        self.two_edit_buhege.setMinimumSize(QtCore.QSize(114, 28))
        self.two_edit_buhege.setMaximumSize(QtCore.QSize(114, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.two_edit_buhege.setFont(font)
        self.two_edit_buhege.setObjectName("two_edit_buhege")
        self.gridLayout_2.addWidget(self.two_edit_buhege, 2, 2, 1, 1)
        self.two_edit_hege = QtWidgets.QLineEdit(self.layoutWidget1)
        self.two_edit_hege.setMinimumSize(QtCore.QSize(114, 28))
        self.two_edit_hege.setMaximumSize(QtCore.QSize(114, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.two_edit_hege.setFont(font)
        self.two_edit_hege.setObjectName("two_edit_hege")
        self.gridLayout_2.addWidget(self.two_edit_hege, 1, 2, 1, 1)
        self.two_now_quekao = QtWidgets.QLabel(self.layoutWidget1)
        self.two_now_quekao.setMinimumSize(QtCore.QSize(70, 30))
        self.two_now_quekao.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.two_now_quekao.setFont(font)
        self.two_now_quekao.setObjectName("two_now_quekao")
        self.gridLayout_2.addWidget(self.two_now_quekao, 5, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_13.setMinimumSize(QtCore.QSize(70, 30))
        self.label_13.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 4, 0, 1, 1)
        self.two_edit_huankao = QtWidgets.QLineEdit(self.layoutWidget1)
        self.two_edit_huankao.setMinimumSize(QtCore.QSize(114, 28))
        self.two_edit_huankao.setMaximumSize(QtCore.QSize(114, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.two_edit_huankao.setFont(font)
        self.two_edit_huankao.setObjectName("two_edit_huankao")
        self.gridLayout_2.addWidget(self.two_edit_huankao, 4, 2, 1, 1)
        self.two_now_huankao = QtWidgets.QLabel(self.layoutWidget1)
        self.two_now_huankao.setMinimumSize(QtCore.QSize(70, 30))
        self.two_now_huankao.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.two_now_huankao.setFont(font)
        self.two_now_huankao.setObjectName("two_now_huankao")
        self.gridLayout_2.addWidget(self.two_now_huankao, 4, 1, 1, 1)
        self.two_edit_quekao = QtWidgets.QLineEdit(self.layoutWidget1)
        self.two_edit_quekao.setMinimumSize(QtCore.QSize(114, 28))
        self.two_edit_quekao.setMaximumSize(QtCore.QSize(114, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.two_edit_quekao.setFont(font)
        self.two_edit_quekao.setObjectName("two_edit_quekao")
        self.gridLayout_2.addWidget(self.two_edit_quekao, 5, 2, 1, 1)
        self.two_edit_mianxiu = QtWidgets.QLineEdit(self.layoutWidget1)
        self.two_edit_mianxiu.setMinimumSize(QtCore.QSize(114, 28))
        self.two_edit_mianxiu.setMaximumSize(QtCore.QSize(114, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.two_edit_mianxiu.setFont(font)
        self.two_edit_mianxiu.setObjectName("two_edit_mianxiu")
        self.gridLayout_2.addWidget(self.two_edit_mianxiu, 3, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setMinimumSize(QtCore.QSize(70, 30))
        self.label_11.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 6, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_12.setMinimumSize(QtCore.QSize(70, 30))
        self.label_12.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 5, 0, 1, 1)
        self.two_now_quxiaozige = QtWidgets.QLabel(self.layoutWidget1)
        self.two_now_quxiaozige.setMinimumSize(QtCore.QSize(70, 30))
        self.two_now_quxiaozige.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.two_now_quxiaozige.setFont(font)
        self.two_now_quxiaozige.setObjectName("two_now_quxiaozige")
        self.gridLayout_2.addWidget(self.two_now_quxiaozige, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setMinimumSize(QtCore.QSize(70, 30))
        self.label_7.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setMinimumSize(QtCore.QSize(70, 30))
        self.label_5.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setMinimumSize(QtCore.QSize(70, 30))
        self.label_6.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 1, 1, 1)
        self.btn_two_confirm = QtWidgets.QPushButton(self.groupBox_two)
        self.btn_two_confirm.setGeometry(QtCore.QRect(110, 410, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_two_confirm.setFont(font)
        self.btn_two_confirm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_two_confirm.setObjectName("btn_two_confirm")
        self.label_tip_2 = QtWidgets.QLabel(self.groupBox_two)
        self.label_tip_2.setGeometry(QtCore.QRect(50, 30, 261, 41))
        self.label_tip_2.setObjectName("label_tip_2")

        self.retranslateUi(MapDialog)
        QtCore.QMetaObject.connectSlotsByName(MapDialog)

    def retranslateUi(self, MapDialog):
        _translate = QtCore.QCoreApplication.translate
        MapDialog.setWindowTitle(_translate("MapDialog", "更改分数映射"))
        self.btn_hundred.setText(_translate("MapDialog", "百分制"))
        self.btn_five.setText(_translate("MapDialog", "五级制"))
        self.btn_two.setText(_translate("MapDialog", "两级制"))
        self.label.setText(_translate("MapDialog", "请选择需要更改的选项"))
        self.groupBox_five.setTitle(_translate("MapDialog", "五级制"))
        self.label_2.setText(_translate("MapDialog", "页面选择"))
        self.label_4.setText(_translate("MapDialog", "当前"))
        self.label_3.setText(_translate("MapDialog", "更改"))
        self.label_17.setText(_translate("MapDialog", "优秀"))
        self.five_now_you.setText(_translate("MapDialog", "_"))
        self.label_22.setText(_translate("MapDialog", "良好"))
        self.five_now_liang.setText(_translate("MapDialog", "_"))
        self.label_20.setText(_translate("MapDialog", "中等"))
        self.five_now_zhong.setText(_translate("MapDialog", "_"))
        self.label_18.setText(_translate("MapDialog", "及格"))
        self.five_now_jige.setText(_translate("MapDialog", "_"))
        self.label_21.setText(_translate("MapDialog", "不及格"))
        self.five_now_bujige.setText(_translate("MapDialog", "_"))
        self.label_19.setText(_translate("MapDialog", "免修"))
        self.five_now_mianxiu.setText(_translate("MapDialog", "_"))
        self.label_23.setText(_translate("MapDialog", "缓考"))
        self.five_now_huankao.setText(_translate("MapDialog", "_"))
        self.label_9.setText(_translate("MapDialog", "缺考"))
        self.five_now_quekao.setText(_translate("MapDialog", "_"))
        self.label_10.setText(_translate("MapDialog", "取消资格"))
        self.five_now_quxiaozige.setText(_translate("MapDialog", "_"))
        self.btn_five_confirm.setText(_translate("MapDialog", "确定"))
        self.label_tip.setText(_translate("MapDialog", "填写需要更改的即可"))
        self.groupBox_hundred.setTitle(_translate("MapDialog", "百分制"))
        self.hundred_double_checkBox.setText(_translate("MapDialog", "点击启用录入分数为小数形式"))
        self.btn_hundred_confirm.setText(_translate("MapDialog", "确定"))
        self.groupBox_two.setTitle(_translate("MapDialog", "两级制"))
        self.label_15.setText(_translate("MapDialog", "不合格"))
        self.two_now_hege.setText(_translate("MapDialog", "_"))
        self.two_now_buhege.setText(_translate("MapDialog", "_"))
        self.label_16.setText(_translate("MapDialog", "合格"))
        self.label_14.setText(_translate("MapDialog", "免修"))
        self.two_now_mianxiu.setText(_translate("MapDialog", "_"))
        self.two_now_quekao.setText(_translate("MapDialog", "_"))
        self.label_13.setText(_translate("MapDialog", "缓考"))
        self.two_now_huankao.setText(_translate("MapDialog", "_"))
        self.label_11.setText(_translate("MapDialog", "取消资格"))
        self.label_12.setText(_translate("MapDialog", "缺考"))
        self.two_now_quxiaozige.setText(_translate("MapDialog", "_"))
        self.label_7.setText(_translate("MapDialog", "更改"))
        self.label_5.setText(_translate("MapDialog", "页面选择"))
        self.label_6.setText(_translate("MapDialog", "当前"))
        self.btn_two_confirm.setText(_translate("MapDialog", "确定"))
        self.label_tip_2.setText(_translate("MapDialog", "填写需要更改的即可"))

